# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [1]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.arange(10) 
# np.arange(15,25)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Step 3. Reshape 1D to 2D Array

In [8]:
arr2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Step 4. Create a Linspace array

In [12]:
np.linspace([1,2,3,4,5],stop=3)
np.linspace(10,15)
# default 50 generate thay linspace ma
np.linspace(10,15,10)

array([10.        , 10.55555556, 11.11111111, 11.66666667, 12.22222222,
       12.77777778, 13.33333333, 13.88888889, 14.44444444, 15.        ])

### Step 5. Create a Random Numbered Array

In [ ]:
np.random.rand(10)
np.random.rand(10).reshape(5,2)

array([[0.52232547, 0.45485861],
       [0.26190944, 0.47290684],
       [0.47627329, 0.49977741],
       [0.18837176, 0.35979122],
       [0.26910127, 0.96156119]])

In [19]:
np.random.rand(5,5)

array([[0.62597702, 0.02403652, 0.34168597, 0.92527028, 0.83116104],
       [0.77464858, 0.06586341, 0.68291243, 0.26679643, 0.43134874],
       [0.796818  , 0.93326501, 0.64120455, 0.62090542, 0.64946189],
       [0.67351416, 0.57790853, 0.81852584, 0.78371262, 0.81803222],
       [0.02982652, 0.17184293, 0.85164951, 0.51899314, 0.70618081]])

### Step 6. Create a Random Integer Array

In [32]:
a = np.random.randint(10,20,size=5)
a

array([16, 11, 14, 14, 12], dtype=int32)

In [27]:
a = np.random.randint(10,20,6)
a = np.random.randint(10,20,size=(5,5))
a

array([[15, 15, 10, 15, 17],
       [10, 11, 14, 10, 14],
       [18, 10, 12, 17, 19],
       [14, 16, 16, 13, 13],
       [15, 14, 19, 14, 15]], dtype=int32)

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [40]:
a = np.random.rand(10,20,5)
a

array([[[5.49589135e-01, 3.59086531e-02, 3.83660365e-01, 3.32375902e-01,
         8.23750346e-01],
        [5.07070739e-01, 5.73332993e-01, 6.80808725e-01, 8.23462258e-01,
         4.31337216e-01],
        [3.51664186e-01, 7.74312155e-01, 6.19230870e-01, 1.28866932e-02,
         7.15794946e-01],
        [7.31445886e-01, 9.63080515e-01, 3.91691202e-01, 2.99260924e-01,
         4.26795439e-02],
        [6.26845930e-02, 9.92596087e-01, 6.37658583e-01, 9.26799607e-01,
         9.01155755e-01],
        [1.58165650e-01, 4.96791581e-01, 8.26188929e-01, 3.41595919e-01,
         8.51177125e-01],
        [2.03449288e-01, 2.05740671e-01, 4.58536810e-01, 1.64623095e-01,
         9.82333938e-01],
        [1.08809262e-01, 7.47181094e-01, 9.66801743e-02, 4.78718236e-01,
         1.42443007e-01],
        [3.86525244e-01, 5.12035826e-02, 3.18368338e-01, 1.24774395e-01,
         1.53310110e-01],
        [8.97728663e-01, 4.77231550e-03, 2.94627922e-02, 3.93149910e-01,
         6.57621200e-01],
        [9.95389716e-01, 9.31095675e-01, 8.14460868e-01, 1.87259831e-01,
         5.54891490e-03],
        [2.72200141e-01, 1.44568909e-01, 3.34458452e-01, 3.33423612e-01,
         8.19754908e-01],
        [8.85961055e-02, 6.33954773e-01, 2.04487988e-01, 2.01898480e-01,
         3.58299517e-01],
        [4.73666460e-01, 7.01767846e-01, 9.27584366e-01, 9.52863510e-01,
         3.57461148e-01],
        [9.99209703e-01, 8.82576873e-01, 1.64709734e-01, 4.69077099e-01,
         7.17629246e-01],
        [6.22504485e-01, 3.06606892e-01, 2.30360907e-01, 6.44180559e-01,
         9.41630483e-01],
        [5.81858063e-01, 4.39025741e-01, 7.77354000e-01, 1.57914820e-01,
         2.53963305e-01],
        [2.23602125e-01, 5.26868679e-01, 7.28213281e-01, 7.04740885e-01,
         9.68443905e-01],
        [1.15127910e-01, 5.75822142e-01, 1.21623666e-01, 4.02145927e-01,
         3.18195047e-04],
        [3.03925300e-01, 7.26677229e-01, 4.01184856e-01, 3.94299584e-01,
         6.45691406e-02]],

       [[8.24942433e-01, 7.19877874e-01, 8.35692056e-01, 5.02745962e-01,
         9.29935624e-01],
        [7.41905989e-01, 8.74124850e-01, 6.15265234e-01, 4.31918208e-01,
         6.99541653e-01],
        [5.53241333e-01, 1.68378384e-01, 6.01169108e-01, 2.48767534e-01,
         8.46028986e-01],
        [6.25388780e-01, 4.56637444e-01, 2.69718401e-01, 1.04488985e-01,
         6.99067416e-01],
        [5.39453941e-01, 9.44744574e-01, 5.13976967e-01, 3.57377197e-01,
         2.70046376e-01],
        [8.02061677e-02, 2.00212896e-01, 7.53049615e-01, 1.91322024e-01,
         9.36809835e-01],
        [7.50054690e-01, 1.53678357e-01, 7.88855129e-01, 9.56491035e-01,
         9.83671397e-01],
        [5.54283156e-01, 6.45806290e-01, 9.39038466e-01, 2.71467525e-02,
         3.53707856e-01],
        [5.32728229e-01, 4.84649255e-01, 8.46531165e-01, 4.24564702e-02,
         7.44613290e-01],
        [7.55958044e-01, 2.02216757e-01, 1.83425705e-01, 2.59097755e-01,
         5.46458683e-02],
        [9.85474348e-02, 2.96230047e-01, 9.60439339e-01, 5.08736892e-01,
         5.87953606e-01],
        [2.13350934e-01, 4.84639892e-01, 2.64515107e-01, 2.82969635e-01,
         7.85702317e-01],
        [1.21741983e-01, 8.71178961e-01, 8.36899706e-01, 3.26322299e-01,
         2.06597468e-01],
        [6.20705670e-01, 2.74084625e-01, 6.38162308e-01, 4.77331341e-01,
         4.78123097e-01],
        [6.10320131e-01, 9.91682992e-01, 6.62523429e-01, 9.27282957e-01,
         5.80615998e-01],
        [8.08912023e-01, 7.39522203e-01, 3.97595633e-01, 2.84923041e-01,
         6.82676882e-01],
        [8.99787206e-01, 4.58167723e-01, 1.48751478e-01, 4.11776672e-01,
         5.80782342e-01],
        [4.22085512e-01, 9.64475834e-01, 2.12138751e-01, 7.97184595e-01,
         6.80944026e-01],
        [8.54660201e-01, 1.65933203e-01, 4.47848528e-01, 1.65353200e-01,
         6.13349759e-01],
        [3.36676185e-01, 3.81973990e-01, 1.36068444e-01, 9.13078314e-01,
         9.53860262e-01]],

       [[9.90605263e-01, 4.63693864e-02, 6.16217689e-01, 1.49729986e-01,
         1.54230280e-01],
        [8.99498161e-01, 5.17038289e-01, 9.02941065e-01, 7.95862921e-02,
         3.47354984e-01],
        [2.07116477e-01, 7.57456671e-01, 8.89972486e-01, 7.78550782e-01,
         3.41796877e-01],
        [4.65881011e-01, 4.92787180e-01, 5.81784830e-01, 4.38518046e-01,
         4.42228593e-01],
        [7.45054425e-01, 5.29928836e-01, 7.95978750e-01, 4.43505418e-01,
         1.55224876e-01],
        [9.96182392e-01, 5.98456885e-01, 9.30226132e-01, 6.03763645e-02,
         5.26306943e-02],
        [6.33853115e-01, 8.38224166e-01, 5.24501684e-01, 5.49222817e-01,
         1.89866306e-01],
        [3.18053872e-01, 3.15909810e-01, 2.99019286e-01, 8.27518561e-01,
         4.78984656e-01],
        [2.26538647e-01, 4.40332697e-01, 1.64312548e-01, 4.52639900e-01,
         9.83709285e-01],
        [6.29104768e-01, 2.86448238e-01, 6.07694934e-01, 3.89192133e-01,
         2.52948069e-01],
        [6.83299060e-01, 7.50676779e-01, 2.59526949e-01, 2.73866548e-01,
         3.52465680e-01],
        [6.05333824e-01, 2.67270921e-01, 4.26627513e-01, 2.81191456e-01,
         1.58261104e-01],
        [1.41802644e-01, 3.01663302e-01, 2.97421108e-02, 8.87228740e-01,
         3.70735265e-01],
        [2.91390948e-01, 3.80236287e-01, 3.23947900e-01, 4.47148459e-01,
         7.69662577e-01],
        [9.15422739e-01, 2.21426951e-01, 1.94810063e-01, 9.55056377e-01,
         1.70222331e-01],
        [4.40981275e-01, 4.26643229e-01, 1.48048589e-01, 6.95823219e-01,
         8.88527711e-01],
        [2.08581294e-01, 6.74835673e-01, 4.12723109e-01, 2.15262732e-01,
         8.40484692e-01],
        [1.58766204e-01, 5.05841151e-01, 4.93229969e-02, 5.38820839e-01,
         7.72872071e-02],
        [8.03406047e-01, 4.20273944e-01, 1.67306756e-01, 2.72653084e-01,
         6.06372477e-02],
        [3.88514360e-01, 3.67131136e-01, 1.06857277e-01, 2.21522290e-02,
         1.51652468e-01]],

       [[7.36425883e-01, 3.17641322e-01, 6.89132437e-01, 1.32412953e-02,
         2.07313779e-01],
        [2.83716851e-02, 9.78276053e-01, 2.11548893e-01, 2.16557806e-02,
         1.00902435e-02],
        [2.55835085e-01, 9.97932996e-01, 9.90480472e-01, 8.17504518e-01,
         2.14363258e-01],
        [8.31089776e-01, 6.63396990e-01, 9.25618493e-01, 3.57976210e-01,
         8.45870246e-02],
        [4.42620179e-01, 1.64344595e-01, 1.85893222e-01, 2.45525858e-01,
         7.16034920e-01],
        [5.84721574e-01, 4.53373958e-01, 9.82903631e-01, 1.67164293e-01,
         5.98046652e-02],
        [9.53868341e-01, 5.80520414e-02, 6.61187584e-02, 6.14028068e-01,
         9.67444288e-01],
        [4.93073574e-01, 8.21223115e-01, 3.05801968e-01, 4.69240135e-02,
         6.99068214e-01],
        [1.05119045e-01, 6.37642673e-01, 9.66461067e-02, 7.44644172e-01,
         7.47886889e-01],
        [7.61372230e-01, 5.08024477e-02, 4.03798366e-01, 7.75793248e-01,
         4.21137364e-01],
        [4.19256590e-01, 3.04176323e-01, 6.27679637e-01, 9.21861566e-01,
         6.62830286e-01],
        [6.56908089e-01, 7.61284834e-01, 1.53504315e-01, 8.11711048e-02,
         2.56773048e-01],
        [8.45012394e-02, 4.27281000e-01, 9.94878134e-01, 4.47687093e-01,
         9.95590594e-01],
        [4.64187602e-01, 4.57771419e-01, 9.36847856e-01, 5.29688911e-01,
         2.74458426e-01],
        [9.80141273e-01, 7.02334918e-01, 1.56706120e-01, 4.43008201e-01,
         9.29928480e-01],
        [2.59053910e-01, 5.96106556e-01, 5.88070836e-01, 6.37752489e-01,
         8.66965458e-01],
        [7.10491531e-01, 2.19855759e-01, 2.19303865e-01, 3.36825734e-01,
         1.51624185e-01],
        [5.03952649e-01, 6.26381002e-01, 3.76883777e-01, 2.61966753e-01,
         7.28207974e-03],
        [8.25889099e-02, 5.08067084e-01, 9.54741188e-01, 9.09130761e-01,
         3.46556410e-01],
        [8.69749627e-01, 9.87520478e-01, 1.14964296e-01, 2.37578800e-01,
         2.95871004e-01]],

       [[1.91992457e-01, 5.51993780e-01, 3.11133759e-01, 5.98402598e-01,
         8.57145458e-02],
        [1.04315234e-01, 5.12890241e-01, 4.90025393e-01, 2.93142965e-01,
         6.33939561e-01],
        [5.47417321e-01, 8.36707374e-01, 9.13091629e-01, 1.44318910e-01,
         8.19580878e-01],
        [3.59329265e-01, 9.91550438e-01, 2.09635324e-01, 3.12113459e-01,
         8.69384669e-01],
        [4.71544730e-01, 2.88418051e-01, 8.91258256e-01, 5.76573468e-02,
         6.45679776e-01],
        [3.43904170e-01, 8.21349211e-02, 3.29233257e-01, 7.15887792e-01,
         5.86357343e-01],
        [7.28441623e-01, 1.29842664e-01, 9.87712805e-01, 5.90388549e-01,
         2.67341675e-01],
        [1.05915115e-01, 1.04794915e-02, 4.14926473e-01, 4.19220716e-01,
         4.48940396e-01],
        [6.22837761e-01, 6.47632012e-01, 7.25671978e-01, 3.72798206e-01,
         7.10732249e-01],
        [5.84647004e-01, 4.49152357e-01, 3.17274700e-01, 1.79032651e-01,
         1.83584840e-01],
        [6.25008595e-01, 4.08035965e-01, 2.36064443e-01, 3.09484822e-01,
         5.22680370e-02],
        [3.88949844e-01, 3.08536952e-01, 9.16561753e-01, 8.26240739e-01,
         7.18783040e-01],
        [9.27064912e-01, 8.16082055e-02, 7.05559757e-01, 3.01352263e-01,
         9.05970819e-01],
        [1.80454685e-01, 1.56030494e-01, 7.71882818e-01, 8.72054883e-01,
         8.55626901e-01],
        [2.25423882e-01, 8.47856803e-01, 7.34992617e-01, 1.44280231e-01,
         3.99555547e-01],
        [2.38684478e-01, 2.06065608e-01, 9.93158647e-01, 1.01177014e-01,
         8.65047651e-01],
        [9.24836451e-01, 3.11385782e-01, 1.49175743e-01, 8.23814988e-01,
         7.35767904e-01],
        [5.94567987e-01, 7.78863016e-01, 3.54723410e-01, 2.54431413e-01,
         5.43408652e-01],
        [2.42892284e-01, 4.96627568e-01, 3.55465635e-01, 2.40860189e-01,
         3.46180565e-01],
        [4.25787154e-01, 3.40119948e-01, 5.82428752e-01, 8.34524965e-01,
         3.04914933e-01]],

       [[4.89503158e-01, 4.43493335e-01, 7.91437472e-01, 4.22553602e-01,
         4.00626132e-01],
        [6.16407894e-01, 5.38203384e-01, 1.67277925e-02, 3.87528753e-02,
         1.08936558e-01],
        [3.44636683e-01, 6.23248061e-01, 7.25387074e-01, 4.92110990e-01,
         7.11837255e-01],
        [2.62621842e-01, 6.68389917e-01, 8.70801367e-01, 2.23776607e-01,
         4.14489319e-01],
        [5.31583213e-01, 7.17523016e-01, 8.74091298e-01, 7.65098382e-01,
         5.27471343e-02],
        [9.11635643e-01, 4.34931532e-01, 3.15384747e-02, 2.36906868e-01,
         7.32701142e-01],
        [5.38871856e-01, 6.38713875e-01, 6.00267122e-01, 6.33482669e-01,
         3.60624444e-01],
        [5.86436104e-01, 4.41708968e-01, 9.48452087e-01, 6.39360589e-01,
         3.45193803e-01],
        [1.04110978e-01, 2.67795141e-01, 7.47155876e-01, 1.45776893e-01,
         7.25212823e-01],
        [6.31608211e-01, 2.87903775e-01, 8.93265007e-01, 9.05353300e-01,
         8.33559167e-01],
        [9.53733307e-01, 6.14174994e-01, 9.98629072e-01, 9.72100030e-01,
         2.69732331e-01],
        [5.24223904e-01, 3.42726607e-02, 1.30161509e-01, 9.17884451e-02,
         9.55693323e-01],
        [9.39502821e-01, 3.32445518e-01, 5.42515020e-01, 1.97772083e-01,
         4.25897702e-01],
        [7.25615776e-01, 6.28168803e-02, 3.65880362e-03, 8.00308597e-01,
         1.86614417e-02],
        [5.42476069e-01, 4.15353771e-02, 2.85431524e-01, 2.12618831e-01,
         4.48932564e-01],
        [9.40746804e-01, 7.74843403e-01, 4.79455808e-01, 3.74925792e-01,
         2.23826492e-01],
        [7.24508367e-01, 6.77456339e-01, 3.98808562e-01, 5.02569047e-02,
         3.58371811e-02],
        [3.67463435e-01, 5.02140857e-01, 7.29899496e-01, 8.93745886e-01,
         1.70480327e-01],
        [8.26362216e-01, 1.85674595e-01, 1.26166871e-01, 1.65073758e-01,
         7.24943905e-01],
        [8.57435864e-01, 9.66845479e-01, 4.86383014e-01, 1.12516942e-01,
         9.95317263e-02]],

       [[1.62926830e-01, 1.71216565e-01, 2.58234301e-01, 3.31787198e-01,
         1.19170954e-01],
        [1.89071847e-01, 5.94410238e-01, 1.84361746e-01, 1.12667069e-01,
         5.38077542e-02],
        [7.32482914e-01, 8.01585840e-01, 4.72188284e-01, 7.19863911e-01,
         5.52117333e-01],
        [9.61855045e-01, 4.40701169e-01, 3.79711011e-01, 2.38098026e-02,
         4.47627320e-01],
        [8.21564082e-01, 2.18440045e-01, 5.64867624e-01, 7.04533241e-01,
         5.36773363e-01],
        [6.95578486e-01, 5.09409759e-01, 2.47530125e-01, 9.99529829e-01,
         7.52821859e-01],
        [6.77276494e-01, 6.65734594e-01, 5.33361007e-01, 1.62046144e-01,
         6.73338759e-01],
        [3.14222239e-01, 9.98377502e-01, 5.17091325e-01, 2.72983704e-01,
         2.69125348e-01],
        [1.77558817e-01, 8.29095764e-01, 5.45840885e-01, 8.11378120e-01,
         6.78446515e-01],
        [2.33670506e-01, 5.11433084e-01, 7.36478758e-01, 9.61910424e-01,
         4.02194125e-02],
        [3.89631920e-01, 7.65634635e-01, 5.24270004e-01, 4.05210391e-01,
         8.74161676e-01],
        [7.98402010e-01, 2.06274002e-01, 6.37245681e-02, 8.97801747e-01,
         4.55856846e-01],
        [5.91319692e-01, 1.57218987e-01, 7.26297405e-01, 1.70105457e-01,
         6.98739549e-01],
        [8.54886690e-01, 2.47005889e-01, 6.19214128e-01, 6.20690201e-01,
         8.16246436e-01],
        [1.22757524e-01, 2.27846302e-01, 2.01533164e-01, 1.06401285e-01,
         8.39906308e-01],
        [2.43635869e-01, 8.48638618e-02, 1.99929394e-01, 3.55383755e-01,
         9.00514582e-01],
        [1.24948966e-01, 1.19220689e-01, 9.70864948e-01, 7.56456850e-01,
         3.01716330e-01],
        [7.06345845e-01, 3.51397365e-01, 9.37473888e-01, 5.82896933e-01,
         3.21415703e-02],
        [1.39827552e-01, 8.21655472e-01, 9.69052478e-01, 1.60520459e-01,
         7.45978214e-01],
        [9.55008324e-01, 6.86853546e-03, 7.75180257e-01, 2.13135136e-01,
         5.77427499e-01]],

       [[2.71765705e-01, 8.63318302e-01, 6.71016590e-01, 6.88972019e-01,
         5.27164604e-01],
        [1.51681512e-01, 6.38768602e-02, 1.11526700e-01, 3.89420352e-01,
         3.08597921e-01],
        [6.30196841e-01, 4.87537916e-01, 1.16402252e-01, 4.75405724e-01,
         2.68892316e-01],
        [1.39336036e-01, 5.00272014e-01, 4.29406231e-01, 8.98221583e-01,
         6.42452681e-01],
        [5.12828015e-01, 3.11720139e-01, 9.68588742e-01, 7.51734073e-01,
         1.68828148e-01],
        [8.47154203e-01, 4.18984662e-01, 6.68189125e-01, 9.26277543e-01,
         2.20500913e-01],
        [7.40235404e-02, 2.42080517e-02, 9.29957854e-01, 3.97430441e-01,
         7.20241939e-01],
        [6.06180111e-02, 8.16160405e-01, 2.15035134e-01, 3.66631664e-01,
         8.99401185e-01],
        [7.27482574e-01, 3.54528826e-01, 1.61421018e-01, 3.66200172e-01,
         2.06711934e-01],
        [2.49097492e-01, 8.94230726e-01, 7.22575445e-01, 1.61998641e-01,
         9.89196624e-01],
        [9.95743947e-01, 9.11058893e-01, 6.79521139e-01, 7.08771692e-02,
         3.78211287e-01],
        [6.39141719e-01, 6.92233817e-01, 8.93847383e-01, 9.75916211e-01,
         2.39571391e-01],
        [3.02741822e-01, 1.78069487e-01, 4.72415294e-01, 5.26134567e-01,
         6.43972518e-01],
        [2.58816083e-01, 2.39151440e-01, 4.39967919e-01, 7.09195579e-01,
         9.89019357e-02],
        [5.42299282e-01, 5.27672817e-01, 6.82343801e-01, 2.90397655e-01,
         7.57541312e-01],
        [9.38903754e-01, 9.79681446e-02, 9.20777281e-01, 1.98504055e-01,
         7.02251419e-01],
        [1.14108554e-01, 3.77015101e-01, 4.60229003e-01, 8.13772710e-01,
         3.11527609e-02],
        [3.22061652e-01, 3.28179038e-01, 8.71179663e-01, 2.14211154e-01,
         2.92086533e-01],
        [6.44336270e-01, 1.99878460e-01, 8.86275204e-01, 5.27603156e-01,
         7.60620341e-01],
        [3.04332575e-02, 9.06163439e-01, 6.85932156e-01, 5.62810717e-01,
         6.42016875e-01]],

       [[9.14145920e-01, 3.53904970e-01, 3.23818841e-01, 6.63382665e-01,
         3.38700564e-01],
        [2.27749903e-01, 5.42881806e-01, 8.50076905e-02, 3.34008822e-01,
         9.95495009e-01],
        [1.16390860e-01, 8.03944376e-01, 9.49541307e-01, 8.19446783e-01,
         2.15304244e-01],
        [3.33292142e-01, 4.11512582e-01, 5.54707156e-02, 4.31291342e-01,
         1.74053435e-02],
        [8.03541642e-01, 5.06153873e-01, 5.52721104e-01, 7.89291225e-01,
         4.51518756e-01],
        [7.61155186e-01, 9.63812125e-01, 6.85224295e-01, 3.56672863e-01,
         6.35658121e-01],
        [6.18995397e-01, 5.39264606e-01, 4.88525992e-01, 8.38447569e-01,
         6.79452861e-01],
        [8.75798000e-01, 7.57108841e-01, 7.37546077e-01, 1.67090852e-01,
         9.64042265e-01],
        [4.85489623e-01, 2.90531309e-01, 8.06592729e-01, 8.09906140e-01,
         2.55843970e-01],
        [3.11762312e-01, 3.33695464e-01, 6.95281663e-02, 5.70150410e-01,
         8.57090357e-02],
        [7.56044313e-01, 2.61610523e-01, 2.35436838e-01, 1.36380379e-02,
         8.39953691e-01],
        [6.47431005e-01, 8.71988787e-02, 3.20317994e-01, 5.58341944e-01,
         2.18596334e-01],
        [3.72388939e-01, 9.25139713e-01, 7.06262009e-01, 8.37401991e-01,
         2.82921894e-01],
        [7.92155051e-01, 7.39937791e-01, 9.16104829e-01, 6.92124758e-01,
         2.25660772e-02],
        [3.38530880e-01, 5.74717135e-01, 4.67362845e-01, 5.64762091e-03,
         9.22558395e-01],
        [4.75806347e-01, 9.77153389e-01, 3.43884772e-02, 9.56641660e-01,
         1.38474258e-01],
        [6.75161568e-01, 9.56521235e-01, 9.37593573e-01, 6.15320552e-01,
         8.82244754e-01],
        [9.23405712e-01, 8.54373619e-01, 9.25576727e-01, 6.51532509e-01,
         5.70002280e-01],
        [4.11808968e-01, 2.86158498e-01, 9.94517989e-01, 2.13265975e-01,
         7.24456998e-01],
        [8.01185856e-01, 2.86407932e-01, 4.66860064e-01, 8.79212692e-01,
         9.84529667e-03]],

       [[1.30278053e-01, 4.06764271e-01, 2.29351378e-02, 3.93765993e-01,
         4.26987414e-01],
        [5.12081607e-01, 5.07630907e-01, 7.22008677e-01, 3.45593737e-01,
         4.04172677e-01],
        [8.30180429e-01, 8.86084708e-02, 7.43715100e-01, 2.63269728e-01,
         4.84904851e-01],
        [6.06850697e-01, 4.01986752e-01, 9.55700921e-02, 4.11506885e-01,
         6.23818490e-01],
        [2.70719762e-01, 8.50414793e-01, 5.41424171e-01, 5.81539288e-01,
         5.08614743e-01],
        [1.05856087e-01, 1.12458623e-01, 9.21165333e-01, 6.07758505e-02,
         8.56375163e-01],
        [2.90688909e-01, 2.32505458e-01, 1.01101788e-02, 3.06227427e-01,
         5.58513889e-01],
        [8.42868596e-01, 1.24227734e-01, 4.59213287e-01, 3.42718143e-02,
         3.93678560e-01],
        [6.33233156e-01, 6.89290616e-01, 9.38119906e-01, 6.03820632e-01,
         3.96516221e-01],
        [9.74867475e-01, 5.27415441e-01, 7.18115567e-01, 6.56915210e-01,
         8.13559835e-01],
        [8.48427447e-01, 3.76412438e-01, 8.79577592e-02, 7.55891748e-01,
         6.99076187e-01],
        [5.25188563e-01, 1.01275077e-03, 1.40712440e-01, 1.04423113e-01,
         5.26031855e-01],
        [2.51451252e-01, 5.39266383e-01, 4.21264612e-01, 9.31456116e-01,
         2.17128248e-01],
        [9.40514172e-01, 8.74003410e-01, 1.95198547e-01, 8.68850760e-01,
         8.89397318e-01],
        [8.04300989e-01, 9.61038811e-02, 9.13425583e-01, 6.40462374e-01,
         6.38361287e-01],
        [1.56880463e-01, 6.11052461e-01, 5.72827876e-01, 6.65111050e-01,
         2.35196510e-01],
        [7.29556188e-01, 1.62656233e-01, 6.00256080e-01, 5.95742723e-01,
         3.82035208e-01],
        [8.59412138e-01, 3.53613740e-01, 2.90808143e-01, 1.17200594e-01,
         7.28629652e-01],
        [6.62019340e-01, 6.68972366e-01, 2.17382817e-01, 2.28163272e-01,
         2.67378635e-01],
        [4.09351367e-01, 2.76275779e-01, 8.19794396e-01, 2.18297660e-02,
         3.53266072e-01]]])

In [42]:
a.max()

np.float64(0.9995298294990507)

In [43]:
a.min()

np.float64(0.0003181950472594952)

In [ ]:
a.argmax()  #give highest value index

np.int64(628)

In [ ]:
a.argmin() #give lowest value index

np.int64(94)

### Step 8. Indexing in 1D Array

In [48]:
arr

array([1, 2, 3, 4, 5])

In [50]:
arr[0] = 10
arr

array([10,  2,  3,  4,  5])

In [59]:
arr[1:4]

array([2, 3, 4])

### Step 9. Indexing in 2D Array

In [54]:
arr2 = arr2.reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
arr2[1][1]

np.int64(3)

### Step 10. Conditional Selection

In [70]:
arr = np.random.randint(20,40,10)
arr

array([36, 39, 38, 39, 31, 29, 39, 26, 25, 23], dtype=int32)

In [74]:
arr>25

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [78]:
arr[(arr>25) & (arr<35)]

array([31, 29, 26], dtype=int32)

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [79]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [87]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep='|',index_col='user_id')
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [88]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [89]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [92]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [93]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [97]:
d = users.columns
d

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [99]:
e =users.index
e

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [103]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [106]:
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [113]:
len(users.occupation.unique())
users['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [116]:
users['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [117]:
users['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

In [118]:
users['occupation'].value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

In [120]:
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [121]:
users.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [124]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [126]:
users.age.mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [127]:
users.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

In [128]:
users.age.value_counts().idxmin()

np.int64(7)

### You're not just learning, you're mastering it. Keep aiming higher! 🚀